const KEY="autoloop_v03";
const seed=[
{id:1,name:"Kit plaquettes de frein avant",brand:"Brembo",vehicle:"Renault Mégane III 1.5 dCi",price:69.90,stock:8,seller:"AutoParts Pro"},
{id:2,name:"Filtre à huile",brand:"Bosch",vehicle:"Peugeot 308 1.6 HDi",price:12.50,stock:24,seller:"Pièces Express"},
{id:3,name:"Kit distribution + pompe à eau",brand:"SKF",vehicle:"Renault Clio IV 1.5 dCi",price:139.90,stock:4,seller:"AutoParts Pro"},
{id:4,name:"Batterie 70Ah",brand:"Varta",vehicle:"Volkswagen Golf VII 1.6 TDI",price:119,stock:6,seller:"Garage Central"}
];
let db=JSON.parse(localStorage.getItem(KEY)||"null")||{products:seed,cart:[],orders:[],seller:null,accounts:[]};
function save(){localStorage.setItem(KEY,JSON.stringify(db));updateCart()}
function money(n){return n.toLocaleString("fr-FR",{style:"currency",currency:"EUR"})}
function updateCart(){let x=document.querySelector("#cartCount");if(x)x.textContent=db.cart.reduce((a,x)=>a+x.qty,0)}
function show(page){
 let app=document.querySelector("#app");
 if(page==="home")app.innerHTML=home();
 if(page==="catalogue")app.innerHTML=catalogue();
 if(page==="sell")app.innerHTML=sell();
 if(page==="login")app.innerHTML=login();
 if(page==="dashboard")app.innerHTML=dashboard();
 if(page==="addproduct")app.innerHTML=addProduct();
 if(page==="cart")app.innerHTML=cart();
 updateCart();
}
function home(){return `<section class="wrap hero"><div><p class="eyebrow">MARKETPLACE AUTO</p><h1>La bonne pièce.<br><span>Pour la bonne voiture.</span></h1><p class="lead">Pièces détachées automobiles neuves vendues par des professionnels.</p><div class="finder"><select><option>Renault</option><option>Peugeot</option><option>BMW</option></select><select><option>Mégane</option><option>Clio</option><option>308</option></select><select><option>2018</option><option>2019</option><option>2020</option></select><button class="btn primary" onclick="show('catalogue')">Rechercher</button></div></div><div class="hero-card"><span class="eyebrow">AUTOLOOP 0.3</span><strong>Un vrai espace vendeur commence ici.</strong><p>Création de compte, connexion et publication de produits sont maintenant disponibles dans le prototype.</p></div></section>`}
function catalogue(){return `<section class="wrap"><div class="section-title"><div><p class="eyebrow">CATALOGUE</p><h2>Pièces disponibles</h2></div><input class="input" style="max-width:280px" placeholder="Rechercher..." oninput="search(this.value)"></div><div id="products" class="grid">${productCards(db.products)}</div></section>`}
function productCards(list){return list.map(p=>`<article class="product"><div class="pic">PIÈCE AUTO</div><div class="pbody"><div class="small">${p.brand} · ${p.seller}</div><h3>${p.name}</h3><div class="small">${p.vehicle}</div><div class="price">${money(p.price)}</div><div class="small">Stock : ${p.stock}</div><div class="row"><button class="btn primary" style="flex:1" ${p.stock<1?"disabled":""} onclick="add(${p.id})">Ajouter</button><button class="btn dark" onclick="details(${p.id})">Voir</button></div></div></article>`).join("")||`<div class="empty">Aucun produit trouvé.</div>`}
function search(q){document.querySelector("#products").innerHTML=productCards(db.products.filter(p=>(p.name+p.brand+p.vehicle+p.seller).toLowerCase().includes(q.toLowerCase())))}
function add(id){let p=db.products.find(x=>x.id===id);let i=db.cart.find(x=>x.id===id);if(i)i.qty++;else db.cart.push({id,qty:1});save();alert("Pièce ajoutée au panier.")}
function details(id){let p=db.products.find(x=>x.id===id);alert(`${p.name}\n${p.vehicle}\nVendeur : ${p.seller}\n${money(p.price)}\nStock : ${p.stock}`)}
function cart(){let rows=db.cart.map(i=>{let p=db.products.find(x=>x.id===i.id);return `<tr><td>${p.name}</td><td>${p.seller}</td><td>${i.qty}</td><td>${money(p.price*i.qty)}</td><td><button class="btn" onclick="removeCart(${p.id})">×</button></td></tr>`}).join("");let total=db.cart.reduce((s,i)=>s+db.products.find(p=>p.id===i.id).price*i.qty,0);return `<section class="wrap"><p class="eyebrow">COMMANDE</p><h2>Panier</h2>${rows?`<table class="table"><tr><th>Produit</th><th>Vendeur</th><th>Qté</th><th>Total</th><th></th></tr>${rows}</table><div style="text-align:right;margin-top:25px"><div class="total">${money(total)}</div><button class="btn primary" onclick="checkout()">Créer la commande</button></div>`:`<div class="empty">Votre panier est vide.</div>`}</section>`}
function removeCart(id){db.cart=db.cart.filter(x=>x.id!==id);save();show("cart")}
function checkout(){if(!db.cart.length)return;let total=db.cart.reduce((s,i)=>s+db.products.find(p=>p.id===i.id).price*i.qty,0);db.orders.push({id:"AL-"+Date.now().toString().slice(-6),date:new Date().toLocaleDateString("fr-FR"),total,status:"En préparation"});db.cart=[];save();alert("Commande créée (paiement encore simulé).");show("dashboard")}
function sell(){return `<section class="wrap"><div class="auth"><p class="eyebrow">PROFESSIONNELS</p><h2>Vendez sur AUTOLOOP</h2><p class="muted">Créez votre compte vendeur. Le compte est actuellement stocké localement pour le prototype.</p><form class="card form" onsubmit="register(event)"><label>Entreprise</label><input id="rname" class="input" required placeholder="Auto Pièces 94"><label>Email</label><input id="remail" class="input" type="email" required placeholder="contact@entreprise.fr"><label>Mot de passe</label><input id="rpass" class="input" type="password" minlength="6" required placeholder="6 caractères minimum"><label>Ville</label><input id="rcity" class="input" required placeholder="Paris"><br><button class="btn primary">Créer mon compte vendeur</button></form><p>Déjà inscrit ? <span class="smalllink" onclick="show('login')">Se connecter</span></p></div></section>`}
function register(e){e.preventDefault();if(db.accounts.some(a=>a.email===remail.value)){alert("Cet email existe déjà.");return}let a={id:Date.now(),name:rname.value,email:remail.value,pass:rpass.value,city:rcity.value};db.accounts.push(a);db.seller={...a};save();alert("Compte vendeur créé.");show("dashboard")}
function login(){return `<section class="wrap"><div class="auth"><p class="eyebrow">CONNEXION</p><h2>Espace vendeur</h2><form class="card form" onsubmit="doLogin(event)"><label>Email</label><input id="lemail" class="input" type="email" required><label>Mot de passe</label><input id="lpass" class="input" type="password" required><br><button class="btn primary">Se connecter</button></form><p>Pas encore de compte ? <span class="smalllink" onclick="show('sell')">Créer un compte</span></p></div></section>`}
function doLogin(e){e.preventDefault();let a=db.accounts.find(x=>x.email===lemail.value&&x.pass===lpass.value);if(!a){alert("Email ou mot de passe incorrect.");return}db.seller={...a};save();show("dashboard")}
function dashboard(){if(!db.seller)return login();let mine=db.products.filter(p=>p.seller===db.seller.name);return `<section class="wrap"><div class="seller-head"><div><p class="eyebrow">ESPACE VENDEUR</p><h2>${db.seller.name}</h2><p class="muted">${db.seller.email} · ${db.seller.city}</p></div><button class="btn danger-btn" onclick="logout()">Déconnexion</button></div><div class="two"><div class="card"><h3>Mes produits</h3><div class="total">${mine.length}</div><p class="muted">produits publiés</p><button class="btn primary" onclick="show('addproduct')">+ Ajouter une pièce</button></div><div class="card"><h3>Commandes</h3><div class="total">${db.orders.length}</div><p class="muted">commandes du prototype</p></div></div><br><h3>Mon catalogue</h3>${mine.length?`<table class="table"><tr><th>Produit</th><th>Prix</th><th>Stock</th></tr>${mine.map(p=>`<tr><td>${p.name}<br><span class="small">${p.vehicle}</span></td><td>${money(p.price)}</td><td>${p.stock}</td></tr>`).join("")}</table>`:`<div class="empty">Aucune pièce. Ajoute ton premier produit.</div>`}</section>`}
function addProduct(){if(!db.seller)return login();return `<section class="wrap"><div class="form"><p class="eyebrow">VENDEUR</p><h2>Ajouter une pièce</h2><form class="card" onsubmit="publish(event)"><label>Nom de la pièce</label><input id="pname" class="input" required placeholder="Ex. Plaquettes de frein avant"><label>Marque</label><input id="pbrand" class="input" required placeholder="Brembo"><label>Véhicule compatible</label><input id="pvehicle" class="input" required placeholder="Renault Mégane III 1.5 dCi"><label>Prix (€)</label><input id="pprice" class="input" type="number" step="0.01" min="0" required><label>Stock</label><input id="pstock" class="input" type="number" min="0" required><br><br><button class="btn primary">Publier la pièce</button></form></div></section>`}
function publish(e){e.preventDefault();db.products.unshift({id:Date.now(),name:pname.value,brand:pbrand.value,vehicle:pvehicle.value,price:Number(pprice.value),stock:Number(pstock.value),seller:db.seller.name});save();alert("Produit publié dans le catalogue.");show("dashboard")}
function logout(){db.seller=null;save();show("home")}
show("home");
