const KEY="autoloop_v02";
const seed=[
{id:1,name:"Kit plaquettes de frein avant",brand:"Brembo",vehicle:"Renault Mégane III 1.5 dCi",price:69.90,stock:8,seller:"AutoParts Pro"},
{id:2,name:"Filtre à huile",brand:"Bosch",vehicle:"Peugeot 308 1.6 HDi",price:12.50,stock:24,seller:"Pièces Express"},
{id:3,name:"Kit distribution + pompe à eau",brand:"SKF",vehicle:"Renault Clio IV 1.5 dCi",price:139.90,stock:4,seller:"AutoParts Pro"},
{id:4,name:"Batterie 70Ah",brand:"Varta",vehicle:"Volkswagen Golf VII 1.6 TDI",price:119,stock:6,seller:"Garage Central"},
{id:5,name:"Filtre à air moteur",brand:"Mann-Filter",vehicle:"BMW Série 3 320d",price:24.90,stock:12,seller:"Pièces Express"},
{id:6,name:"Disque de frein avant",brand:"ATE",vehicle:"Renault Mégane IV 1.5 dCi",price:54.90,stock:10,seller:"Garage Central"}
];
let db=JSON.parse(localStorage.getItem(KEY)||"null")||{products:seed,cart:[],orders:[],seller:null};
function save(){localStorage.setItem(KEY,JSON.stringify(db));updateCart()}
function money(n){return n.toLocaleString("fr-FR",{style:"currency",currency:"EUR"})}
function updateCart(){document.querySelector("#cartCount").textContent=db.cart.reduce((a,x)=>a+x.qty,0)}
function show(page){
 const app=document.querySelector("#app");
 if(page==="home") app.innerHTML=home();
 if(page==="catalogue") app.innerHTML=catalogue();
 if(page==="sell") app.innerHTML=sell();
 if(page==="dashboard") app.innerHTML=dashboard();
 if(page==="cart") app.innerHTML=cart();
 updateCart();
}
function home(){return `<section class="wrap hero"><div><p class="eyebrow">MARKETPLACE AUTO</p><h1>La bonne pièce.<br><span>Pour la bonne voiture.</span></h1><p class="lead">Une marketplace dédiée aux pièces détachées automobiles neuves vendues par des professionnels.</p><div class="finder"><select><option>Renault</option><option>Peugeot</option><option>BMW</option></select><select><option>Mégane</option><option>Clio</option><option>308</option></select><select><option>2018</option><option>2019</option><option>2020</option></select><button class="btn primary" onclick="show('catalogue')">Rechercher</button></div></div><div class="hero-card"><span class="eyebrow">MVP</span><strong>Vendeurs professionnels → acheteurs</strong><p class="muted">Catalogue, panier, commandes et espace vendeur sont déjà simulés dans cette version.</p></div></section>`}
function catalogue(){return `<section class="wrap"><div class="section-title"><div><p class="eyebrow">CATALOGUE</p><h2>Pièces disponibles</h2></div><input class="input" style="max-width:280px" placeholder="Rechercher..." oninput="search(this.value)"></div><div id="products" class="grid">${productCards(db.products)}</div></section>`}
function productCards(list){return list.map(p=>`<article class="product"><div class="pic">PIÈCE AUTO</div><div class="pbody"><div class="small">${p.brand} · ${p.seller}</div><h3>${p.name}</h3><div class="small">${p.vehicle}</div><div class="price">${money(p.price)}</div><div class="row"><button class="btn primary" style="flex:1" onclick="add(${p.id})">Ajouter</button><button class="btn dark" onclick="details(${p.id})">Voir</button></div></div></article>`).join("")||`<div class="empty">Aucun produit trouvé.</div>`}
function search(q){document.querySelector("#products").innerHTML=productCards(db.products.filter(p=>(p.name+p.brand+p.vehicle+p.seller).toLowerCase().includes(q.toLowerCase())))}
function add(id){const p=db.products.find(x=>x.id===id);let item=db.cart.find(x=>x.id===id);if(item)item.qty++;else db.cart.push({id,qty:1});save();alert("Pièce ajoutée au panier.");}
function details(id){const p=db.products.find(x=>x.id===id);alert(`${p.name}\n${p.vehicle}\nVendeur : ${p.seller}\nPrix : ${money(p.price)}\nStock : ${p.stock}`)}
function cart(){let rows=db.cart.map(i=>{let p=db.products.find(x=>x.id===i.id);return `<tr><td>${p.name}</td><td>${p.seller}</td><td>${i.qty}</td><td>${money(p.price*i.qty)}</td><td><button class="btn" onclick="remove(${p.id})">×</button></td></tr>`}).join("");let total=db.cart.reduce((s,i)=>s+db.products.find(p=>p.id===i.id).price*i.qty,0);return `<section class="wrap"><p class="eyebrow">COMMANDE</p><h2>Votre panier</h2>${rows?`<table class="table"><tr><th>Produit</th><th>Vendeur</th><th>Qté</th><th>Total</th><th></th></tr>${rows}</table><div style="text-align:right;margin-top:25px"><div class="total">${money(total)}</div><button class="btn primary" onclick="checkout()">Passer commande</button></div>`:`<div class="empty">Votre panier est vide.</div>`}</section>`}
function remove(id){db.cart=db.cart.filter(x=>x.id!==id);save();show("cart")}
function checkout(){if(!db.cart.length)return;const total=db.cart.reduce((s,i)=>s+db.products.find(p=>p.id===i.id).price*i.qty,0);db.orders.push({id:"AL-"+Date.now().toString().slice(-6),date:new Date().toLocaleDateString("fr-FR"),total,status:"En préparation"});db.cart=[];save();alert("Commande créée dans le prototype. Le vrai paiement sera connecté à l'étape suivante.");show("dashboard")}
function sell(){return `<section class="wrap"><p class="eyebrow">VENDEUR</p><h2>Rejoindre AUTOLOOP</h2><p class="muted">Cette version permet de créer une fiche vendeur locale. Ensuite nous connecterons les vrais comptes et l'import catalogue.</p><form class="card form" onsubmit="createSeller(event)"><label>Nom de l'entreprise</label><input class="input" id="sname" required placeholder="Ex. Auto Pièces 94"><label>Email professionnel</label><input class="input" id="semail" type="email" required placeholder="contact@entreprise.fr"><label>Nombre de références</label><input class="input" id="scount" type="number" min="1" required placeholder="500"><label>Ville</label><input class="input" id="scity" required placeholder="Paris"><br><br><button class="btn primary">Créer mon profil vendeur</button></form></section>`}
function createSeller(e){e.preventDefault();db.seller={name:sname.value,email:semail.value,count:scount.value,city:scity.value};save();alert("Profil vendeur créé dans le prototype.");show("dashboard")}
function dashboard(){let seller=db.seller;let orderRows=db.orders.map(o=>`<tr><td>${o.id}</td><td>${o.date}</td><td>${money(o.total)}</td><td><span class="pill">${o.status}</span></td></tr>`).join("");return `<section class="wrap"><p class="eyebrow">ESPACE</p><h2>Tableau de bord</h2><div class="two"><div class="card"><h3>Vendeur</h3>${seller?`<p><b>${seller.name}</b><br>${seller.email}<br>${seller.city}<br>${seller.count} références annoncées</p>`:`<p class="muted">Aucun vendeur enregistré.</p>`}<button class="btn primary" onclick="show('sell')">${seller?"Modifier":"Devenir vendeur"}</button></div><div class="card"><h3>Commandes</h3><div class="total">${db.orders.length}</div><p class="muted">commandes dans le prototype</p></div></div><br><h3>Historique des commandes</h3>${orderRows?`<table class="table"><tr><th>ID</th><th>Date</th><th>Total</th><th>Statut</th></tr>${orderRows}</table>`:`<div class="empty">Aucune commande.</div>`}</section>`}
show("home");